"use client";

import { useEffect, useMemo, useState } from "react";

import type { DashboardData, TaskRecord } from "@/lib/dashboard-data";

type AgentActionsPanelProps = {
  identity: string;
  profile: DashboardData["profile"];
  tasks: TaskRecord[];
  agenda: DashboardData["agenda"];
  recommendation: DashboardData["recommendation"];
};

type GeneratedBrief = {
  action: "replan" | "pitch" | "slip";
  title: string;
  lines: string[];
  tone: "cyan" | "emerald" | "indigo";
  createdAt: string;
};

function scoreTask(task: TaskRecord) {
  const priorityScore = task.priority === "high" ? 3 : task.priority === "medium" ? 2 : 1;
  const dueScore = task.due_date ? 2 : 0;
  const effortScore = task.estimated_minutes && task.estimated_minutes <= 30 ? 2 : 1;

  return priorityScore + dueScore + effortScore;
}

function formatRoleLabel(category: string) {
  const roles = category
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);

  if (roles.length === 0) {
    return "adaptive";
  }

  if (roles.length === 1) {
    return roles[0];
  }

  return roles.join(" + ");
}

function exportJSON(history: GeneratedBrief[], profile: AgentActionsPanelProps["profile"]) {
  const payload = {
    exported: new Date().toISOString(),
    project: "Pathly — Design4Future 2026",
    account: profile.fullName,
    category: profile.category,
    goal: profile.mainGoal,
    actions: history,
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `pathly-ai-timeline-${new Date().toISOString().slice(0, 10)}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportText(history: GeneratedBrief[], profile: AgentActionsPanelProps["profile"]) {
  const lines: string[] = [
    "PATHLY — AI DECISION TIMELINE",
    `Exported: ${new Date().toLocaleString()}`,
    `Account: ${profile.fullName} · ${profile.category}`,
    `Goal: ${profile.mainGoal}`,
    "─────────────────────────────────────",
    "",
  ];

  for (const item of history) {
    const ts = new Date(item.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
    lines.push(`[${ts}] ${item.title.toUpperCase()}`);
    for (const line of item.lines) {
      lines.push(`  - ${line}`);
    }
    lines.push("");
  }

  lines.push("─────────────────────────────────────");
  lines.push("Generated by Pathly AI Orchestration Layer");

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `pathly-ai-timeline-${new Date().toISOString().slice(0, 10)}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function AgentActionsPanel({ identity, profile, tasks, agenda, recommendation }: AgentActionsPanelProps) {
  const [brief, setBrief] = useState<GeneratedBrief | null>(null);
  const [history, setHistory] = useState<GeneratedBrief[]>([]);

  const storageKey = useMemo(() => `pathly:ai-actions:${identity.toLowerCase()}`, [identity]);

  useEffect(() => {
    const raw = globalThis.localStorage?.getItem(storageKey);
    if (!raw) {
      return;
    }

    try {
      const parsed = JSON.parse(raw) as GeneratedBrief[];
      if (Array.isArray(parsed)) {
        setHistory(parsed.slice(0, 8));
      }
    } catch {
      setHistory([]);
    }
  }, [storageKey]);

  const saveHistory = (next: GeneratedBrief) => {
    setHistory((current) => {
      const updated = [next, ...current].slice(0, 8);
      globalThis.localStorage?.setItem(storageKey, JSON.stringify(updated));
      return updated;
    });
  };

  const openTasks = useMemo(
    () => [...tasks.filter((task) => task.status !== "completed")].sort((left, right) => scoreTask(right) - scoreTask(left)),
    [tasks],
  );

  const generateReplan = () => {
    const topThree = openTasks.slice(0, 3);
    const lines = [
      `Replan timestamp: ${new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`,
      `Primary move: ${topThree[0]?.title ?? recommendation.title}`,
      ...topThree.map((task, index) => {
        const minutes = task.estimated_minutes ?? 25;
        return `Block ${String(index + 1).padStart(2, "0")}: ${task.title} (${minutes}m)`;
      }),
      "Rule: complete one block fully before switching to reduce context loss.",
    ];

    setBrief({
      action: "replan",
      title: "Agenda Replanned",
      lines,
      tone: "cyan",
      createdAt: new Date().toISOString(),
    });

    saveHistory({
      action: "replan",
      title: "Agenda Replanned",
      lines,
      tone: "cyan",
      createdAt: new Date().toISOString(),
    });
  };

  const generateJudgePitch = () => {
    const activeTasks = openTasks.length;
    const doneTasks = tasks.filter((task) => task.status === "completed").length;
    const topAgenda = agenda[0]?.title ?? recommendation.title;
    const completionRate = tasks.length > 0 ? Math.round((doneTasks / tasks.length) * 100) : 0;
    const roleLabel = formatRoleLabel(profile.category);
    const topTask = openTasks[0]?.title ?? recommendation.title;
    const secondTask = openTasks[1]?.title;

    const nextBrief: GeneratedBrief = {
      action: "pitch",
      title: "90s Judge Pitch",
      lines: [
        `Problem: most planners store work, but they do not decide what should happen first when a ${roleLabel.toLowerCase()} user is overloaded.`,
        `Differentiator: Pathly adapts the plan to live role context, then surfaces one next move instead of another flat task wall.`,
        `Proof on this account: ${doneTasks} of ${tasks.length} tasks completed (${completionRate}%); ${activeTasks} active task${activeTasks !== 1 ? "s" : ""}; top priority is ${topAgenda}.`,
        `Recommendation engine: right now it is choosing ${recommendation.title} because ${recommendation.reason.toLowerCase()}.`,
        secondTask
          ? `Demo magic moment: switch this profile or role mix and watch the stack reorder from ${topTask} to a different priority lane such as ${secondTask}.`
          : `Demo magic moment: switch the profile context and the recommendation lane updates immediately without rebuilding the workflow.`,
        `Why it can win: explainable AI, multi-role planning, and a live working product instead of a concept-only mockup.`,
      ],
      tone: "indigo",
      createdAt: new Date().toISOString(),
    };

    setBrief(nextBrief);
    saveHistory(nextBrief);
  };

  const generateSlipPlan = () => {
    const primary = openTasks[0];
    const fallback = openTasks[1];
    const defer = openTasks
      .slice(2)
      .filter((task) => task.priority !== "high")
      .slice(0, 2)
      .map((task) => task.title);

    const lines = [
      primary
        ? `If ${primary.title} slips by 30m, preserve outcome quality and cut scope, not clarity.`
        : "No active primary task found. Add a task to enable slip recovery.",
      fallback
        ? `Switch immediately to: ${fallback.title} to keep momentum while blockers are resolved.`
        : "No fallback task is available; create one medium-effort backup task.",
      defer.length > 0
        ? `Defer lower-risk items: ${defer.join("; ")}.`
        : "No safe defer candidate found, so split the main task into two smaller checkpoints.",
      "After recovery, run Replan now to update sequence and confidence.",
    ];

    const nextBrief: GeneratedBrief = {
      action: "slip",
      title: "Slip Recovery Plan",
      lines,
      tone: "emerald",
      createdAt: new Date().toISOString(),
    };

    setBrief(nextBrief);
    saveHistory(nextBrief);
  };

  const toneClasses =
    brief?.tone === "emerald"
      ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-100"
      : brief?.tone === "indigo"
        ? "border-indigo-500/30 bg-indigo-500/10 text-indigo-100"
        : "border-cyan-500/30 bg-cyan-500/10 text-cyan-100";

  return (
    <section className="rounded-3xl border border-slate-700/30 bg-slate-900/40 px-5 py-5">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <p className="text-xs font-semibold tracking-[0.2em] text-slate-300 uppercase">AI action center</p>
        <span className="text-xs text-slate-500">One click responses</span>
      </div>

      <div className="mt-3 flex flex-col gap-2 sm:flex-row sm:flex-wrap">
        <button
          type="button"
          onClick={generateReplan}
          className="rounded-full border border-cyan-500/35 bg-cyan-500/10 px-4 py-2 text-xs font-semibold text-cyan-200 transition-colors hover:border-cyan-400/60 hover:text-cyan-100"
        >
          Replan my day now
        </button>
        <button
          type="button"
          onClick={generateJudgePitch}
          className="rounded-full border border-indigo-500/35 bg-indigo-500/10 px-4 py-2 text-xs font-semibold text-indigo-200 transition-colors hover:border-indigo-400/60 hover:text-indigo-100"
        >
          Generate 90s judge pitch
        </button>
        <button
          type="button"
          onClick={generateSlipPlan}
          className="rounded-full border border-emerald-500/35 bg-emerald-500/10 px-4 py-2 text-xs font-semibold text-emerald-200 transition-colors hover:border-emerald-400/60 hover:text-emerald-100"
        >
          If task slips, rebalance
        </button>
      </div>

      {brief ? (
        <div className={`mt-4 rounded-2xl border px-4 py-3 ${toneClasses}`}>
          <p className="text-xs font-semibold tracking-[0.18em] uppercase">{brief.title}</p>
          <ul className="mt-2 space-y-1.5 text-xs leading-5">
            {brief.lines.map((line) => (
              <li key={line}>- {line}</li>
            ))}
          </ul>
        </div>
      ) : (
        <p className="mt-4 text-xs text-slate-500">
          Trigger one action to see live AI output based on your current priorities, constraints, and execution status.
        </p>
      )}

      <div className="mt-4 rounded-2xl border border-slate-700/40 bg-slate-950/50 px-4 py-3">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <p className="text-[11px] font-semibold tracking-[0.18em] text-slate-400 uppercase">AI decision timeline</p>
          <div className="flex items-center gap-2">
            {history.length > 0 ? (
              <>
                <button
                  type="button"
                  onClick={() => exportJSON(history, profile)}
                  className="rounded-full border border-slate-600/40 bg-slate-800/50 px-2.5 py-1 text-[11px] font-semibold text-slate-300 transition-colors hover:border-cyan-500/50 hover:text-cyan-200"
                >
                  Export JSON
                </button>
                <button
                  type="button"
                  onClick={() => exportText(history, profile)}
                  className="rounded-full border border-slate-600/40 bg-slate-800/50 px-2.5 py-1 text-[11px] font-semibold text-slate-300 transition-colors hover:border-indigo-500/50 hover:text-indigo-200"
                >
                  Export proof
                </button>
              </>
            ) : null}
            <span className="text-[11px] text-slate-500">last 8 actions</span>
          </div>
        </div>

        {history.length > 0 ? (
          <ul className="mt-2 space-y-2">
            {history.map((item) => {
              const time = new Date(item.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
              const toneText =
                item.tone === "emerald"
                  ? "text-emerald-300"
                  : item.tone === "indigo"
                    ? "text-indigo-300"
                    : "text-cyan-300";

              return (
                <li key={`${item.createdAt}-${item.title}`} className="rounded-xl border border-slate-800/70 bg-slate-900/60 px-3 py-2">
                  <div className="flex items-center justify-between gap-2">
                    <p className={`text-xs font-semibold ${toneText}`}>{item.title}</p>
                    <span className="text-[11px] text-slate-500">{time}</span>
                  </div>
                  <p className="mt-1 text-xs leading-5 text-slate-400 line-clamp-2">{item.lines[0]}</p>
                </li>
              );
            })}
          </ul>
        ) : (
          <p className="mt-2 text-xs text-slate-500">No actions yet. Trigger a button above to start tracking AI decisions.</p>
        )}
      </div>
    </section>
  );
}
